### ISSUE TITLE
Cleanup cmake configs

### ISSUE THREAD

**Issue by hanhossain** [hanhossain/chakra-rs#36]
- [x] Remove from cmake configs:
  - [x] #39
  - [x] CC_TARGETS_X86 #41 
  - [x] CC_TARGETS_ARM #44
  - [x] CC_XCODE_PROJECT #43
  - [x] COMPILER_IS_GNU #40
  - [x] USE_LTTNG #45
  - [x] EMBED_ICU #52
  - [x] LIBS_ONLY_BUILD #42
  - [x] CCACHE_PROGRAM_NAME #46
  - [x] CCACHE_PROGRAM #46
  - [x] ENABLE_VALGRIND #47
  - [x] ENABLE_CC_XPLAT_TRACE #48
  - [x] ENABLE_FULL_LTO #49
  - [x] ENABLE_THIN_LTO #49
  - [x] WITHOUT_FEATURES #50
  - [x] EXTRA_DEFINES #50
  - [x] CLANG_SANITIZE #50
  - [x] ENABLE_JS_LTTNG #51
- [x] Remove but keep in code files:
  - [x] WIN32 #40
  - [x] MINGW #40
  - [x] COMPILER_IS_MSVC #40
  - [x] COMPILER_IS_CLANG (make sure to set it on config, but don't use conditionals) #40
- [x] Remaining with `TODO (hanhossain): marked for cleanup` #53
